### ISSUE TITLE
Slider crashes when single child is passed

### ISSUE THREAD

**Issue by steve192** [bushblade/react-touch-drag-slider#1]
Hi,

I wanted to use your slider in one of my projects and found that it crashes whenever a single child element is passed to the slider component.

`Uncaught TypeError: children.map is not a function`

The cause should be in
https://github.com/bushblade/react-touch-drag-slider/blob/8eb333042514023110ccfaf9dbf2850978090e22/src/components/Slider.jsx#L176

where it is expected that children is an array. 

If you want I can try to make a pullrequest to fix this?

**Comment by bushblade** [comment]
Hi @steve192 
Thanks for the issue.
To be honest I've not done much with this project for a while so yes if you want to submit a PR, I'll take a look.

**Comment by steve192** [comment]
Hi @bushblade 
In the meantime I switched to another library's and unfortunately most likely won't fix this bug.
Shall we close this issue or leave it open for others?

**Comment by bushblade** [comment]
I'll close as I think expecting more than one child would be appropriate for a slider anyway.

**Comment by danielblnc** [comment]
Pull Request: https://github.com/bushblade/react-touch-drag-slider/pull/4
