### ISSUE TITLE
How to override padding between `Slider` elements? 

### ISSUE THREAD

**Issue by shannonbonet** [bushblade/react-touch-drag-slider#2]
Hiyah, 
<img width="828" alt="Screen Shot 2022-07-21 at 2 13 05 AM" src="https://user-images.githubusercontent.com/63089231/180142189-4af21e15-07e5-4b69-a411-fedaedac0436.png">
<img width="768" alt="Screen Shot 2022-07-21 at 2 12 45 AM" src="https://user-images.githubusercontent.com/63089231/180142131-83fb3cff-05b0-44b5-8857-e862cabf587f.png">

I want to get rid of padding between elements and I noticed that its div is randomly generated on re-renders so its hard to systematically determine where to override. I've already tried a global div, adding styles to `Slider` directly, and (in vain) tried on individual elements. So far this has been the best carousel package I've tried, so it'd be great to know how to customize :)

**Comment by bdlogicalerror** [comment]
I'm facing the same problem
